language: node_js

notifications:
  email:
    on_success: never
    on_failure: change

node_js:
- stable

before_install:
- export PATH="$(yarn bin):${PATH}"
- yarn global add codecov

before_script:
- cd ts && yarn install

script:
- cd ts
- npm test
- coverage/lcov.info coverage.lcov && codecov
