language: node_js

notifications:
  email:
    on_success: never
    on_failure: change

node_js:
- stable

before_install:
- export PATH="$(yarn bin):${PATH}"
- yarn global add greenkeeper-lockfile@1

before_script:
- greenkeeper-lockfile-update

script:
- npm test
- ./tools/continuous-deployment.travis.sh
- cp coverage/lcov.info coverage.lcov
- node node_modules/.bin/codecov

after_script:
- greenkeeper-lockfile-upload
